$f = "d:\VSCodeRepo\MyLocalAssistant\src\MyLocalAssistant.Client\UI\ChatTranscript.cs"
$lines = Get-Content $f -Encoding UTF8
# Find where OnPaint starts (it's the incomplete line)
$paintLine = ($lines | Select-String -Pattern "protected override void OnPaint").LineNumber
Write-Host "OnPaint at line $paintLine, total lines: $($lines.Count)"
# Keep only up to and including "protected override void OnPaint(PaintEventArgs e)"
# then "{" — i.e. keep paintLine lines (0-indexed: 0 .. paintLine+1)
$good = $lines[0..($paintLine)] # 0-indexed, paintLine is 1-indexed so [paintLine] = line paintLine+1 in 1-indexed = the "{" line

$tail = @(
'        e.Graphics.SmoothingMode = SmoothingMode.AntiAlias;',
'        var fill   = GetFill(Kind);',
'        var border = GetBorder(Kind);',
'',
'        using var path = UiTheme.MakeRoundedPath(_bubbleBounds, BubbleRadius);',
'        using (var b = new SolidBrush(fill)) e.Graphics.FillPath(b, path);',
'        if (border != Color.Empty)',
'        {',
'            using var p = new Pen(border, 1f);',
'            e.Graphics.DrawPath(p, path);',
'        }',
'',
'        // Animated dots while waiting for the first token',
'        if (IsStreaming && string.IsNullOrEmpty(_fullText))',
'        {',
'            var baseClr = GetTextColor(Kind);',
'            int cy = _bubbleBounds.Y + _bubbleBounds.Height / 2 - 4;',
'            int cx = _bubbleBounds.X + InnerPadX;',
'            for (int i = 0; i < 3; i++)',
'            {',
'                int alpha = i == _dotsPhase ? 230 : 70;',
'                using var db = new SolidBrush(Color.FromArgb(alpha, baseClr.R, baseClr.G, baseClr.B));',
'                e.Graphics.FillEllipse(db, cx + i * 14, cy, 8, 8);',
'            }',
'        }',
'    }',
'',
'    // Theme refresh',
'',
'    public void RefreshTheme()',
'    {',
'        _mainText.BackColor = GetFill(Kind);',
'        _mainText.ForeColor = GetTextColor(Kind);',
'        _meta.ForeColor     = UiTheme.TextSecondary;',
'        _copyBtn.ForeColor  = UiTheme.TextSecondary;',
'',
'        foreach (var seg in _segControls)',
'        {',
'            if (seg is TextBox tb)',
'            {',
'                tb.BackColor = GetFill(Kind);',
'                tb.ForeColor = GetTextColor(Kind);',
'            }',
'            else if (seg is Panel cp && cp.Tag is CodePanelRefs refs)',
'            {',
'                var codeBg = UiTheme.CodeBlockBg;',
'                var codeFg = UiTheme.IsDark ? Color.FromArgb(200, 200, 200) : Color.FromArgb(30, 30, 30);',
'                cp.BackColor           = codeBg;',
'                refs.CodeBox.BackColor = codeBg;',
'                refs.CodeBox.ForeColor = codeFg;',
'            }',
'        }',
'        Invalidate();',
'    }',
'',
'    private static Color GetFill(BubbleKind k) => k switch',
'    {',
'        BubbleKind.User      => UiTheme.UserBubbleFill,',
'        BubbleKind.Assistant => UiTheme.AssistantBubbleFill,',
'        BubbleKind.Note      => UiTheme.NoteBg,',
'        BubbleKind.Error     => UiTheme.ErrorBg,',
'        _                    => UiTheme.SurfaceCard,',
'    };',
'',
'    private static Color GetTextColor(BubbleKind k) => k switch',
'    {',
'        BubbleKind.User      => Color.White,',
'        BubbleKind.Assistant => UiTheme.TextPrimary,',
'        BubbleKind.Note      => UiTheme.IsDark ? Color.FromArgb(230, 190, 100) : Color.FromArgb(116, 86, 12),',
'        BubbleKind.Error     => UiTheme.Danger,',
'        _                    => UiTheme.TextPrimary,',
'    };',
'',
'    private static Color GetBorder(BubbleKind k) => k switch',
'    {',
'        BubbleKind.Assistant => UiTheme.Border,',
'        BubbleKind.Note      => UiTheme.IsDark ? Color.FromArgb(100, 80, 30) : Color.FromArgb(245, 220, 160),',
'        BubbleKind.Error     => UiTheme.IsDark ? Color.FromArgb(150, 50, 50) : Color.FromArgb(240, 180, 175),',
'        _                    => Color.Empty,',
'    };',
'',
'    protected override void Dispose(bool disposing)',
'    {',
'        if (disposing) _dotsTimer.Dispose();',
'        base.Dispose(disposing);',
'    }',
'}'
)

($good + $tail) | Set-Content $f -Encoding UTF8
Write-Host "Done. Lines: $((Get-Content $f | Measure-Object -Line).Lines)"
